require("./db")
const express=require("express")
require("express-async-error")
const morgan=require("morgan")
const bodyParser=require("body-parser")
const app=express()
app.use(morgan("combined"))
app.use(bodyParser.json())
app.use(require("./middleware/md_res"))
app.use(require("./middleware/token"))
app.use(require("./middleware/permission"))
app.use("/category",require("./router/category"))
app.use("/product",require("./router/product"))
app.use("/order",require("./router/order"))
app.use("/user",require("./router/user"))
app.use((err,req,res,next) => {
    res.fail(err.toString())
    next()
})
const config=require("./config")
app.listen(config.PORT)
